/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : bigint,
  'user' : UserId,
  'achievement' : AchievementType,
  'timestamp' : Time,
}
export type AchievementType = { 'vipLevelUp' : null } |
  { 'referralStar' : null } |
  { 'firstInvestment' : null } |
  { 'firstDeposit' : null } |
  { 'weekStreak' : null };
export interface Activity {
  'id' : bigint,
  'user' : UserId,
  'actionType' : string,
  'description' : string,
  'timestamp' : Time,
}
export type Amount = bigint;
export type Crypto = { 'bnb' : null } |
  { 'eth' : null } |
  { 'trx' : null } |
  { 'usdt' : null };
export interface Deposit {
  'id' : bigint,
  'status' : DepositStatus,
  'user' : UserId,
  'walletAddress' : string,
  'crypto' : Crypto,
  'timestamp' : Time,
  'amount' : Amount,
}
export type DepositStatus = { 'pending' : null } |
  { 'completed' : null };
export interface Investment {
  'id' : bigint,
  'startTime' : Time,
  'active' : boolean,
  'endTime' : Time,
  'planId' : bigint,
  'user' : UserId,
  'amount' : Amount,
}
export interface InvestmentPlan {
  'id' : bigint,
  'maxAmount' : Amount,
  'minAmount' : Amount,
  'name' : string,
  'lockDays' : bigint,
  'dailyReturn' : bigint,
}
export interface Referral {
  'referralCode' : string,
  'referrer' : UserId,
  'referredUser' : UserId,
}
export type Time = bigint;
export interface Trade {
  'id' : bigint,
  'tradeType' : TradeType,
  'exchangePair' : string,
  'timestamp' : Time,
  'amount' : Amount,
  'profitPercent' : bigint,
}
export type TradeType = { 'buy' : null } |
  { 'sell' : null };
export type UserId = Principal;
export interface UserProfile {
  'referralCode' : string,
  'balance' : Amount,
  'vipLevel' : bigint,
  'activeInvestments' : bigint,
  'referredBy' : [] | [string],
  'totalEarnings' : Amount,
  'dailyStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Withdrawal {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'user' : UserId,
  'walletAddress' : string,
  'crypto' : Crypto,
  'timestamp' : Time,
  'amount' : Amount,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'approved' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTrade' : ActorMethod<[string, TradeType, bigint, Amount], Trade>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardAchievement' : ActorMethod<[AchievementType], Achievement>,
  'createDeposit' : ActorMethod<[Crypto, Amount, string], Deposit>,
  'createInvestment' : ActorMethod<[bigint, Amount], Investment>,
  'createWithdrawal' : ActorMethod<[Amount, string, Crypto], Withdrawal>,
  'getAllPlans' : ActorMethod<[], Array<InvestmentPlan>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRecentTrades' : ActorMethod<[], Array<Trade>>,
  'getUserAchievements' : ActorMethod<[UserId], Array<Achievement>>,
  'getUserActivity' : ActorMethod<[UserId], Array<Activity>>,
  'getUserDeposits' : ActorMethod<[UserId], Array<Deposit>>,
  'getUserInvestments' : ActorMethod<[UserId], Array<Investment>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserReferrals' : ActorMethod<[UserId], Array<Referral>>,
  'getUserWithdrawals' : ActorMethod<[UserId], Array<Withdrawal>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logActivity' : ActorMethod<[string, string], Activity>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];