/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TradeType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Amount = IDL.Nat;
export const Time = IDL.Int;
export const Trade = IDL.Record({
  'id' : IDL.Nat,
  'tradeType' : TradeType,
  'exchangePair' : IDL.Text,
  'timestamp' : Time,
  'amount' : Amount,
  'profitPercent' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AchievementType = IDL.Variant({
  'vipLevelUp' : IDL.Null,
  'referralStar' : IDL.Null,
  'firstInvestment' : IDL.Null,
  'firstDeposit' : IDL.Null,
  'weekStreak' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Achievement = IDL.Record({
  'id' : IDL.Nat,
  'user' : UserId,
  'achievement' : AchievementType,
  'timestamp' : Time,
});
export const Crypto = IDL.Variant({
  'bnb' : IDL.Null,
  'eth' : IDL.Null,
  'trx' : IDL.Null,
  'usdt' : IDL.Null,
});
export const DepositStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Deposit = IDL.Record({
  'id' : IDL.Nat,
  'status' : DepositStatus,
  'user' : UserId,
  'walletAddress' : IDL.Text,
  'crypto' : Crypto,
  'timestamp' : Time,
  'amount' : Amount,
});
export const Investment = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'active' : IDL.Bool,
  'endTime' : Time,
  'planId' : IDL.Nat,
  'user' : UserId,
  'amount' : Amount,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
});
export const Withdrawal = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'user' : UserId,
  'walletAddress' : IDL.Text,
  'crypto' : Crypto,
  'timestamp' : Time,
  'amount' : Amount,
});
export const InvestmentPlan = IDL.Record({
  'id' : IDL.Nat,
  'maxAmount' : Amount,
  'minAmount' : Amount,
  'name' : IDL.Text,
  'lockDays' : IDL.Nat,
  'dailyReturn' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Text,
  'balance' : Amount,
  'vipLevel' : IDL.Nat,
  'activeInvestments' : IDL.Nat,
  'referredBy' : IDL.Opt(IDL.Text),
  'totalEarnings' : Amount,
  'dailyStreak' : IDL.Nat,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'user' : UserId,
  'actionType' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const Referral = IDL.Record({
  'referralCode' : IDL.Text,
  'referrer' : UserId,
  'referredUser' : UserId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTrade' : IDL.Func([IDL.Text, TradeType, IDL.Nat, Amount], [Trade], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardAchievement' : IDL.Func([AchievementType], [Achievement], []),
  'createDeposit' : IDL.Func([Crypto, Amount, IDL.Text], [Deposit], []),
  'createInvestment' : IDL.Func([IDL.Nat, Amount], [Investment], []),
  'createWithdrawal' : IDL.Func([Amount, IDL.Text, Crypto], [Withdrawal], []),
  'getAllPlans' : IDL.Func([], [IDL.Vec(InvestmentPlan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRecentTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getUserAchievements' : IDL.Func([UserId], [IDL.Vec(Achievement)], ['query']),
  'getUserActivity' : IDL.Func([UserId], [IDL.Vec(Activity)], ['query']),
  'getUserDeposits' : IDL.Func([UserId], [IDL.Vec(Deposit)], ['query']),
  'getUserInvestments' : IDL.Func([UserId], [IDL.Vec(Investment)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserReferrals' : IDL.Func([UserId], [IDL.Vec(Referral)], ['query']),
  'getUserWithdrawals' : IDL.Func([UserId], [IDL.Vec(Withdrawal)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logActivity' : IDL.Func([IDL.Text, IDL.Text], [Activity], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TradeType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Amount = IDL.Nat;
  const Time = IDL.Int;
  const Trade = IDL.Record({
    'id' : IDL.Nat,
    'tradeType' : TradeType,
    'exchangePair' : IDL.Text,
    'timestamp' : Time,
    'amount' : Amount,
    'profitPercent' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AchievementType = IDL.Variant({
    'vipLevelUp' : IDL.Null,
    'referralStar' : IDL.Null,
    'firstInvestment' : IDL.Null,
    'firstDeposit' : IDL.Null,
    'weekStreak' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Achievement = IDL.Record({
    'id' : IDL.Nat,
    'user' : UserId,
    'achievement' : AchievementType,
    'timestamp' : Time,
  });
  const Crypto = IDL.Variant({
    'bnb' : IDL.Null,
    'eth' : IDL.Null,
    'trx' : IDL.Null,
    'usdt' : IDL.Null,
  });
  const DepositStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Deposit = IDL.Record({
    'id' : IDL.Nat,
    'status' : DepositStatus,
    'user' : UserId,
    'walletAddress' : IDL.Text,
    'crypto' : Crypto,
    'timestamp' : Time,
    'amount' : Amount,
  });
  const Investment = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'active' : IDL.Bool,
    'endTime' : Time,
    'planId' : IDL.Nat,
    'user' : UserId,
    'amount' : Amount,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
  });
  const Withdrawal = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'user' : UserId,
    'walletAddress' : IDL.Text,
    'crypto' : Crypto,
    'timestamp' : Time,
    'amount' : Amount,
  });
  const InvestmentPlan = IDL.Record({
    'id' : IDL.Nat,
    'maxAmount' : Amount,
    'minAmount' : Amount,
    'name' : IDL.Text,
    'lockDays' : IDL.Nat,
    'dailyReturn' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Text,
    'balance' : Amount,
    'vipLevel' : IDL.Nat,
    'activeInvestments' : IDL.Nat,
    'referredBy' : IDL.Opt(IDL.Text),
    'totalEarnings' : Amount,
    'dailyStreak' : IDL.Nat,
  });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'user' : UserId,
    'actionType' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const Referral = IDL.Record({
    'referralCode' : IDL.Text,
    'referrer' : UserId,
    'referredUser' : UserId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTrade' : IDL.Func([IDL.Text, TradeType, IDL.Nat, Amount], [Trade], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardAchievement' : IDL.Func([AchievementType], [Achievement], []),
    'createDeposit' : IDL.Func([Crypto, Amount, IDL.Text], [Deposit], []),
    'createInvestment' : IDL.Func([IDL.Nat, Amount], [Investment], []),
    'createWithdrawal' : IDL.Func([Amount, IDL.Text, Crypto], [Withdrawal], []),
    'getAllPlans' : IDL.Func([], [IDL.Vec(InvestmentPlan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRecentTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getUserAchievements' : IDL.Func(
        [UserId],
        [IDL.Vec(Achievement)],
        ['query'],
      ),
    'getUserActivity' : IDL.Func([UserId], [IDL.Vec(Activity)], ['query']),
    'getUserDeposits' : IDL.Func([UserId], [IDL.Vec(Deposit)], ['query']),
    'getUserInvestments' : IDL.Func([UserId], [IDL.Vec(Investment)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUserReferrals' : IDL.Func([UserId], [IDL.Vec(Referral)], ['query']),
    'getUserWithdrawals' : IDL.Func([UserId], [IDL.Vec(Withdrawal)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logActivity' : IDL.Func([IDL.Text, IDL.Text], [Activity], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };