/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface InvestmentPlan {
    id: bigint;
    maxAmount: Amount;
    minAmount: Amount;
    name: string;
    lockDays: bigint;
    dailyReturn: bigint;
}
export interface Trade {
    id: bigint;
    tradeType: TradeType;
    exchangePair: string;
    timestamp: Time;
    amount: Amount;
    profitPercent: bigint;
}
export interface Investment {
    id: bigint;
    startTime: Time;
    active: boolean;
    endTime: Time;
    planId: bigint;
    user: UserId;
    amount: Amount;
}
export type Amount = bigint;
export interface Achievement {
    id: bigint;
    user: UserId;
    achievement: AchievementType;
    timestamp: Time;
}
export type UserId = Principal;
export interface Activity {
    id: bigint;
    user: UserId;
    actionType: string;
    description: string;
    timestamp: Time;
}
export interface Withdrawal {
    id: bigint;
    status: WithdrawalStatus;
    user: UserId;
    walletAddress: string;
    crypto: Crypto;
    timestamp: Time;
    amount: Amount;
}
export interface Referral {
    referralCode: string;
    referrer: UserId;
    referredUser: UserId;
}
export interface Deposit {
    id: bigint;
    status: DepositStatus;
    user: UserId;
    walletAddress: string;
    crypto: Crypto;
    timestamp: Time;
    amount: Amount;
}
export interface UserProfile {
    referralCode: string;
    balance: Amount;
    vipLevel: bigint;
    activeInvestments: bigint;
    referredBy?: string;
    totalEarnings: Amount;
    dailyStreak: bigint;
}
export enum AchievementType {
    vipLevelUp = "vipLevelUp",
    referralStar = "referralStar",
    firstInvestment = "firstInvestment",
    firstDeposit = "firstDeposit",
    weekStreak = "weekStreak"
}
export enum Crypto {
    bnb = "bnb",
    eth = "eth",
    trx = "trx",
    usdt = "usdt"
}
export enum DepositStatus {
    pending = "pending",
    completed = "completed"
}
export enum TradeType {
    buy = "buy",
    sell = "sell"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WithdrawalStatus {
    pending = "pending",
    completed = "completed",
    approved = "approved"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTrade(exchangePair: string, tradeType: TradeType, profitPercent: bigint, amount: Amount): Promise<Trade>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    awardAchievement(achievement: AchievementType): Promise<Achievement>;
    createDeposit(crypto: Crypto, amount: Amount, walletAddress: string): Promise<Deposit>;
    createInvestment(planId: bigint, amount: Amount): Promise<Investment>;
    createWithdrawal(amount: Amount, walletAddress: string, crypto: Crypto): Promise<Withdrawal>;
    getAllPlans(): Promise<Array<InvestmentPlan>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getRecentTrades(): Promise<Array<Trade>>;
    getUserAchievements(user: UserId): Promise<Array<Achievement>>;
    getUserActivity(user: UserId): Promise<Array<Activity>>;
    getUserDeposits(user: UserId): Promise<Array<Deposit>>;
    getUserInvestments(user: UserId): Promise<Array<Investment>>;
    getUserProfile(user: UserId): Promise<UserProfile | null>;
    getUserReferrals(userId: UserId): Promise<Array<Referral>>;
    getUserWithdrawals(user: UserId): Promise<Array<Withdrawal>>;
    isCallerAdmin(): Promise<boolean>;
    logActivity(actionType: string, description: string): Promise<Activity>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateUserProfile(profile: UserProfile): Promise<void>;
}
import type { Achievement as _Achievement, AchievementType as _AchievementType, Amount as _Amount, Crypto as _Crypto, Deposit as _Deposit, DepositStatus as _DepositStatus, Time as _Time, Trade as _Trade, TradeType as _TradeType, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, Withdrawal as _Withdrawal, WithdrawalStatus as _WithdrawalStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTrade(arg0: string, arg1: TradeType, arg2: bigint, arg3: Amount): Promise<Trade> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrade(arg0, to_candid_TradeType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_Trade_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrade(arg0, to_candid_TradeType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_Trade_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async awardAchievement(arg0: AchievementType): Promise<Achievement> {
        if (this.processError) {
            try {
                const result = await this.actor.awardAchievement(to_candid_AchievementType_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Achievement_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardAchievement(to_candid_AchievementType_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Achievement_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDeposit(arg0: Crypto, arg1: Amount, arg2: string): Promise<Deposit> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeposit(to_candid_Crypto_n15(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_Deposit_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeposit(to_candid_Crypto_n15(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_Deposit_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInvestment(arg0: bigint, arg1: Amount): Promise<Investment> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvestment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvestment(arg0, arg1);
            return result;
        }
    }
    async createWithdrawal(arg0: Amount, arg1: string, arg2: Crypto): Promise<Withdrawal> {
        if (this.processError) {
            try {
                const result = await this.actor.createWithdrawal(arg0, arg1, to_candid_Crypto_n15(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Withdrawal_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWithdrawal(arg0, arg1, to_candid_Crypto_n15(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Withdrawal_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlans(): Promise<Array<InvestmentPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlans();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentTrades(): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentTrades();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentTrades();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAchievements(arg0: UserId): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAchievements(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAchievements(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserActivity(arg0: UserId): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserActivity(arg0);
            return result;
        }
    }
    async getUserDeposits(arg0: UserId): Promise<Array<Deposit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDeposits(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDeposits(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserInvestments(arg0: UserId): Promise<Array<Investment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserInvestments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserInvestments(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserReferrals(arg0: UserId): Promise<Array<Referral>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserReferrals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserReferrals(arg0);
            return result;
        }
    }
    async getUserWithdrawals(arg0: UserId): Promise<Array<Withdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWithdrawals(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWithdrawals(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logActivity(arg0: string, arg1: string): Promise<Activity> {
        if (this.processError) {
            try {
                const result = await this.actor.logActivity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logActivity(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AchievementType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AchievementType): AchievementType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Achievement_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Achievement): Achievement {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Crypto_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Crypto): Crypto {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_DepositStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositStatus): DepositStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Deposit_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deposit): Deposit {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TradeType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeType): TradeType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Withdrawal_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Withdrawal): Withdrawal {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    user: _UserId;
    achievement: _AchievementType;
    timestamp: _Time;
}): {
    id: bigint;
    user: UserId;
    achievement: AchievementType;
    timestamp: Time;
} {
    return {
        id: value.id,
        user: value.user,
        achievement: from_candid_AchievementType_n13(_uploadFile, _downloadFile, value.achievement),
        timestamp: value.timestamp
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DepositStatus;
    user: _UserId;
    walletAddress: string;
    crypto: _Crypto;
    timestamp: _Time;
    amount: _Amount;
}): {
    id: bigint;
    status: DepositStatus;
    user: UserId;
    walletAddress: string;
    crypto: Crypto;
    timestamp: Time;
    amount: Amount;
} {
    return {
        id: value.id,
        status: from_candid_DepositStatus_n19(_uploadFile, _downloadFile, value.status),
        user: value.user,
        walletAddress: value.walletAddress,
        crypto: from_candid_Crypto_n21(_uploadFile, _downloadFile, value.crypto),
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _WithdrawalStatus;
    user: _UserId;
    walletAddress: string;
    crypto: _Crypto;
    timestamp: _Time;
    amount: _Amount;
}): {
    id: bigint;
    status: WithdrawalStatus;
    user: UserId;
    walletAddress: string;
    crypto: Crypto;
    timestamp: Time;
    amount: Amount;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n25(_uploadFile, _downloadFile, value.status),
        user: value.user,
        walletAddress: value.walletAddress,
        crypto: from_candid_Crypto_n21(_uploadFile, _downloadFile, value.crypto),
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    balance: _Amount;
    vipLevel: bigint;
    activeInvestments: bigint;
    referredBy: [] | [string];
    totalEarnings: _Amount;
    dailyStreak: bigint;
}): {
    referralCode: string;
    balance: Amount;
    vipLevel: bigint;
    activeInvestments: bigint;
    referredBy?: string;
    totalEarnings: Amount;
    dailyStreak: bigint;
} {
    return {
        referralCode: value.referralCode,
        balance: value.balance,
        vipLevel: value.vipLevel,
        activeInvestments: value.activeInvestments,
        referredBy: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.referredBy)),
        totalEarnings: value.totalEarnings,
        dailyStreak: value.dailyStreak
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tradeType: _TradeType;
    exchangePair: string;
    timestamp: _Time;
    amount: _Amount;
    profitPercent: bigint;
}): {
    id: bigint;
    tradeType: TradeType;
    exchangePair: string;
    timestamp: Time;
    amount: Amount;
    profitPercent: bigint;
} {
    return {
        id: value.id,
        tradeType: from_candid_TradeType_n5(_uploadFile, _downloadFile, value.tradeType),
        exchangePair: value.exchangePair,
        timestamp: value.timestamp,
        amount: value.amount,
        profitPercent: value.profitPercent
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vipLevelUp: null;
} | {
    referralStar: null;
} | {
    firstInvestment: null;
} | {
    firstDeposit: null;
} | {
    weekStreak: null;
}): AchievementType {
    return "vipLevelUp" in value ? AchievementType.vipLevelUp : "referralStar" in value ? AchievementType.referralStar : "firstInvestment" in value ? AchievementType.firstInvestment : "firstDeposit" in value ? AchievementType.firstDeposit : "weekStreak" in value ? AchievementType.weekStreak : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): DepositStatus {
    return "pending" in value ? DepositStatus.pending : "completed" in value ? DepositStatus.completed : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bnb: null;
} | {
    eth: null;
} | {
    trx: null;
} | {
    usdt: null;
}): Crypto {
    return "bnb" in value ? Crypto.bnb : "eth" in value ? Crypto.eth : "trx" in value ? Crypto.trx : "usdt" in value ? Crypto.usdt : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    approved: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "completed" in value ? WithdrawalStatus.completed : "approved" in value ? WithdrawalStatus.approved : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradeType {
    return "buy" in value ? TradeType.buy : "sell" in value ? TradeType.sell : value;
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Array<Trade> {
    return value.map((x)=>from_candid_Trade_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Achievement>): Array<Achievement> {
    return value.map((x)=>from_candid_Achievement_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Deposit>): Array<Deposit> {
    return value.map((x)=>from_candid_Deposit_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Withdrawal>): Array<Withdrawal> {
    return value.map((x)=>from_candid_Withdrawal_n23(_uploadFile, _downloadFile, x));
}
function to_candid_AchievementType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AchievementType): _AchievementType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Crypto_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Crypto): _Crypto {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_TradeType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): _TradeType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    balance: Amount;
    vipLevel: bigint;
    activeInvestments: bigint;
    referredBy?: string;
    totalEarnings: Amount;
    dailyStreak: bigint;
}): {
    referralCode: string;
    balance: _Amount;
    vipLevel: bigint;
    activeInvestments: bigint;
    referredBy: [] | [string];
    totalEarnings: _Amount;
    dailyStreak: bigint;
} {
    return {
        referralCode: value.referralCode,
        balance: value.balance,
        vipLevel: value.vipLevel,
        activeInvestments: value.activeInvestments,
        referredBy: value.referredBy ? candid_some(value.referredBy) : candid_none(),
        totalEarnings: value.totalEarnings,
        dailyStreak: value.dailyStreak
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AchievementType): {
    vipLevelUp: null;
} | {
    referralStar: null;
} | {
    firstInvestment: null;
} | {
    firstDeposit: null;
} | {
    weekStreak: null;
} {
    return value == AchievementType.vipLevelUp ? {
        vipLevelUp: null
    } : value == AchievementType.referralStar ? {
        referralStar: null
    } : value == AchievementType.firstInvestment ? {
        firstInvestment: null
    } : value == AchievementType.firstDeposit ? {
        firstDeposit: null
    } : value == AchievementType.weekStreak ? {
        weekStreak: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Crypto): {
    bnb: null;
} | {
    eth: null;
} | {
    trx: null;
} | {
    usdt: null;
} {
    return value == Crypto.bnb ? {
        bnb: null
    } : value == Crypto.eth ? {
        eth: null
    } : value == Crypto.trx ? {
        trx: null
    } : value == Crypto.usdt ? {
        usdt: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): {
    buy: null;
} | {
    sell: null;
} {
    return value == TradeType.buy ? {
        buy: null
    } : value == TradeType.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
